version: "3"
services:
    app:
        build: ./zing-mp3-vue
        image: zing-mp3-vue
        container_name: zing-mp3-vue
        restart: always
        environment:
            - VUE_APP_API_BASE=http://localhost:3000/api/v1/
        ports:
            - "80:80"
    api:
        build: ./zing-mp3-api
        image: zing-mp3-api
        container_name: zing-mp3-api
        environment:
            - PORT=3000
        ports:
            - "3000:3000"
